apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-auth
  template:
    metadata:
      labels:
        app: msvc-auth
    spec:
      containers:
        - name: msvc-auth
          image: michaellibarra/msvc-auth:latest
          ports:
            - containerPort: 9000
          env:
            - name: LB_USERS_URI
              valueFrom:
                configMapKeyRef:
                  key: lb_users_uri
                  name: msvc-user
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      # port su alcanza desde el exterior
      port: 9000
        # port en el contenedor
      targetPort: 9000
  selector:
    app: msvc-auth