apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-gateway
  template:
    metadata:
      labels:
        app: msvc-gateway
    spec:
      containers:
        - name: msvc-gateway
          image: michaellibarra/msvc-gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-gateway
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      # port su alcanza desde el exterior
      port: 8090
        # port en el contenedor
      targetPort: 8090
  selector:
    app: msvc-gateway